parameters:
    braunedigital_imagine_proxy: '/'
    liip_imagine.controller.class: 'BrauneDigital\ImagineBundle\Controller\ImagineController'
    liip_imagine.twig.extension.class: 'BrauneDigital\ImagineBundle\Templating\ImagineExtension'
    liip_imagine.cache.manager.class: 'BrauneDigital\ImagineBundle\Imagine\Cache\CacheManager'

services:

    braunedigital.imagine.liip_imagine.filter.crop:
        class: 'BrauneDigital\ImagineBundle\Imagine\Filter\Loader\CropFilterLoader'
        tags:
            - { name: 'liip_imagine.filter.loader', loader: 'braunedigital_imagine_crop' }

    braunedigital.imagine.liip_imagine.filter.resize:
        class: 'BrauneDigital\ImagineBundle\Imagine\Filter\Loader\RelativeResizeFilterLoader'
        tags:
            - { name: 'liip_imagine.filter.loader', loader: 'braunedigital_imagine_resize' }

    braunedigital.imagine.liip_imagine.filter.grayscale:
        class: 'BrauneDigital\ImagineBundle\Imagine\Filter\Loader\GrayScale'
        tags:
            - { name: 'liip_imagine.filter.loader', loader: 'braunedigital_imagine_greyscale' }

    braunedigital.media.resizer.crop:
        class: 'BrauneDigital\ImagineBundle\Resizer\CropResizer'
        arguments: ['@sonata.media.adapter.image.gd', 'outbound', '@sonata.media.metadata.proxy']

    braunedigital.media_extension:
        class: 'BrauneDigital\ImagineBundle\Twig\MediaExtension'
        arguments: ['@sonata.media.pool', '@sonata.media.manager.media']
        tags:
            - { name: twig.extension }

    braunedigital.imagine.cache.resolver.proxy1:
        class: 'Liip\ImagineBundle\Imagine\Cache\Resolver\ProxyResolver'
        arguments:
            - "@liip_imagine.cache.resolver.default"
            - [ '%braunedigital_imagine_proxy%' ]
        tags:
            - { name: 'liip_imagine.cache.resolver', resolver: 'proxy' }